import SearchSide from "./components/SearchSide";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weather-App | Clone",
  description: "Generated by Alok Singh",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className="flex">
      <body className={inter.className}>
        <main className="flex max-md:flex-col ">
          <SearchSide />
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
